### ISSUE TITLE
The faucet is out of funds

### ISSUE THREAD

**Issue by codsmobiles** [pk910/PoWFaucet#141]
Hi guys 
I just started learning software
I start it with node and I get this error.
The faucet is out of funds

My config file is here. I want to operate on the local network.
Which fields do I need to change?
![image](https://github.com/pk910/PoWFaucet/assets/161164250/3fcade2b-cd59-4963-815c-5d1625c2fc12)
![image](https://github.com/pk910/PoWFaucet/assets/161164250/f3cacc01-0c99-45f7-b77a-7b101c5f9476)

```

# Goerli PoWFaucet config
version: 2

### General Settings

# faucet database (defaults to local sqlite)
database:
  driver: "sqlite"
  file: "faucet-store.db"

# logfile for faucet events (comment out for no logging)
faucetLogFile: "faucet-events.log"

# path to file to write the process pid to (comment out to disable)
faucetPidFile: "faucet-pid.txt"

# faucet http/ws server port
serverPort: 8080

# number of http proxies in front of this faucet
httpProxyCount: 0

# title of the faucet
faucetTitle: "Goerli PoW Faucet"

# url to image displayed on the startpage
faucetImage: "/images/fauceth_420.jpg"

# some additional html to show on the startpage
faucetHomeHtml: |
  <div class='pow-info'>
    <h5>What is a PoW Faucet?</h5>
    This is an Ethereum Faucet running on the Goerli Testnet.<br>
    To prevent malicious actors from exhausting all available funds or 
    accumulating enough Ether to mount long running spam attacks, 
    this faucet requires some mining work to be done in exchange for 
    free testnet funds.
  </div>
  <div class='pow-info'>
    <h5>How does this work?</h5>
    Just enter your ETH Address and start mining. 
    When you've collected enough ETH, stop mining and claim your rewards.
  </div>
  <div class='pow-info'>
    <h5>How to help the faucet?</h5>
    Replenish the faucet by sending funds you don't need anymore to:<br>
    {faucetWallet}
  </div>

# random secret string that is used by the faucet to "sign" session data, so sessions can be restored automatically by clients when faucet is restarted / crashed
# use a random string and do not share / reuse it anywhere. Everyone knowing this secret is theoretically able to claim rewards from the faucet without mining.
faucetSecret: "RandomStringThatShouldBeVerySecret!"

# ETH execution layer RPC host
ethRpcHost: "https://goerli.infura.io/v3/************"

# faucet wallet private key (hex, without 0x prefix)
ethWalletKey: " :) "

# EVM chain id (null for auto-detect from RPC)
ethChainId: null

# symbol (short name) of the coin that can be mined
faucetCoinSymbol: "GoETH"

# type of coin that can be mined
# native = native coin (ETH)
# erc20 = ERC20 token
faucetCoinType: "native"

# transaction gas limit
# use 21000 to prevent transactions to contracts
ethTxGasLimit: 21000

# use legacy (non-eip1559) transaction type
# true: Type 0 (Legacy Transactions), false: Type 2 (EIP1559 Transactions)
ethLegacyTx: false

# max transaction gas fee (in wei)
# used as limit for legacy transactions (faucet won't build transactions with higher gas price)
ethTxMaxFee: 100000000000  # 100 gwei

# max transaction priority fee (in wei)
ethTxPrioFee: 2000000000  # 2 gwei

# max number of unconfirmed transactions to create simultaneously
ethMaxPending: 12

# queue transactions and wait for funding when faucet is out of funds (show "No Funds" error when false)
ethQueueNoFunds: true

# link to eth transaction explorer with {txid} as placeholder for transaction id or null for no link
ethTxExplorerLink: "https://goerli.etherscan.io/tx/{txid}"

# min/max drop amount (max is the default if no module lowers it)
maxDropAmount: 1000000000000000000 # 1 ETH
minDropAmount: 10000000000000000 # 0.01 ETH

# maximum session time (from start till payout)
# only relevant if one of the enabled protection mechanisms introduces a session delay (eg. mining)
sessionTimeout: 43200  # 12h

# session cleanup time
# session data will be removed from the faucet DB after that time
sessionCleanup: 2592000 # 30 days

# session save time
# how often session updates will be written to DB
sessionSaveTime: 120

### Protection mechanisms
modules:
  # ... (diğer koruma mekanizmaları burada)

  ## Proof of Work (mining) protection
  pow:
    # ... (diğer PoW ayarları burada)

    # enable / disable PoW protection
    enabled: true

    # reward amount per eligible hash (in wei)
    powShareReward: 2000000000000000  # 0.002 ETH

    # penalty for not responding to a verification request (percent of powShareReward)
    verifyMinerMissPenaltyPerc: 10  # 10% of powShareReward

    # reward for responding to a verification request in time (percent of powShareReward)
    verifyMinerRewardPerc:   15  # 15% of powShareReward

    # maximum mining session time (in seconds)
    powSessionTimeout: 18000   # 5h

    # maximum number of seconds a session can idle until it gets closed
    powIdleTimeout: 1800 # 30min

    # maximum allowed mining hashrate (will be throttled to this rate when faster)
    powHashrateSoftLimit: 1000 # soft limit (enforced client side)
    powHashrateHardLimit: 1100 # hard limit (reject shares with too high nonces)

    # number of 0-bits the scrypt hash needs to start with to be eligible for a reward
    powDifficulty: 11

    # mining algorithm to use
    powHashAlgo: "argon2"  # scrypt / cryptonight / argon2`
```
