### ISSUE TITLE
Gitcoin "humanity score" of 8.1, faucet think it's 0?

### ISSUE THREAD

**Issue by aaronzshey** [pk910/PoWFaucet#258]
Hello there,

I've linked my Gitcoin passport website and connected my various socials to receive a score of 8.1:
<img width="1438" alt="Screen Shot 2024-07-09 at 9 41 02 PM" src="https://github.com/pk910/PoWFaucet/assets/44917034/d977b154-885e-427a-a0c1-9e5784f89942">

However, when I visit the faucet, I get this:
<img width="782" alt="Screen Shot 2024-07-09 at 9 41 34 PM" src="https://github.com/pk910/PoWFaucet/assets/44917034/b9a6dac7-f13f-4ad8-a768-7b35e81d254b">

Which is odd, because I think I do have a gitcoin passport score greater than 2.  However, I am curious about the yellow exclamation point next to "Sepolia": is this an indication that I've done something wrong.

Thanks!

**Comment by pk910** [comment]
Hmm, that should work.
Did you try refreshing the passport? 
It sometimes takes a few mins till new stamps are actually returned by the passport api.

**Comment by aaronzshey** [comment]
Interestingly enough, I just tried today and it worked!  I'm guessing it can take several days for the passport to return updated stamps.  I was going to submit a pull request to add this to the blue banner on the website, but couldn't find the file to edit.  Where would I go to edit the static html part of this website?

**Comment by clauBv23** [comment]
I'm having the same issue, it has been 5 hours, and still stamps are still at 0. :(

**Comment by aaronzshey** [comment]
@clauBv23  - for me, it took the faucet 5 days to receive my updated gitcoin passport.  I'd love to open a pull request and update the banner - @pk910 lmk where in the project structure the banner text is and I can edit it!

**Comment by pk910** [comment]
@aaronzshey 
the banner is not in the codebase itself. It's sideloaded via configuration and currently looks like this:
```yaml
- key: passport
  prio: 6
  text: |
    <span class='nopad' style='font-size:14px;'>
      New sessions require a minimum gitcoin passport score of at least 2.<br>
      Please visit <a href="https://passport.gitcoin.co/#/" target="_blank">Gitcoin Passport</a> to increase your passport score.
    </span>
    <style>.faucet-status-alert:has(.nopad) { padding: 8px; } </style>
  ishtml: true
  level: info
```
